import Ajv from "ajv";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

import { JsonResponseError, UserNotConnectedError } from "./errors";
import {
  ExtendedTool,
  ProxyApiRequestToolArgs,
} from "./type";
import {
  decodeJwt,
  generateSetupLink,
  performAction,
  getTools,
  performOpenApiAction,
  performProxyApiRequest,
  envs,
} from "./utils";
import { getCustomTools, performCustomAction } from "./custom-tools";

const ajv = new Ajv({ allErrors: true, strict: false });

/**
 * Get tools from ActionKit API, append extraTools, and filter by integrations if specified in the environment variables
 * @param jwt - Paragon User Token
 * @param extraTools - Additional tools, e.g. those generated by OpenAPI specs
 */
async function getAndProcessTools(
  jwt: string,
  extraTools: Array<ExtendedTool> = []
): Promise<Array<ExtendedTool>> {
  const dynamicTools = await getTools(jwt);
  const allTools = dynamicTools.concat(extraTools);

  return allTools.filter((tool) => {
    let keep = true;
    if (envs.LIMIT_TO_INTEGRATIONS && envs.LIMIT_TO_INTEGRATIONS.length > 0) {
      keep = keep && envs.LIMIT_TO_INTEGRATIONS.includes(tool.integrationName);
    }
    if (envs.LIMIT_TO_TOOLS && envs.LIMIT_TO_TOOLS.length > 0) {
      keep = keep && envs.LIMIT_TO_TOOLS.includes(tool.name);
    }
    return keep;
  });
}

export function registerTools({
  server,
  currentJwt,
  extraTools = [],
}: {
  server: Server;
  currentJwt: string;
  extraTools?: Array<ExtendedTool>;
}) {
  let cachedTools: Array<ExtendedTool> | undefined;

  server.registerCapabilities({
    tools: {
      listChanged: true,
    },
  });

  server.setRequestHandler(
    ListToolsRequestSchema,
    async () => {
      if (cachedTools) {
        return { tools: cachedTools };
      }

      cachedTools = await getAndProcessTools(currentJwt, extraTools);
      return { tools: cachedTools };
    }
  );

  server.setRequestHandler(
    CallToolRequestSchema,
    async (request) => {
      const { name, arguments: args } = request.params;
      if (!cachedTools) {
        cachedTools = await getAndProcessTools(currentJwt, extraTools);
      }
      const tool = cachedTools.find((candidate) => candidate.name === name);
      if (!tool) {
        throw new Error(`Tool not found: ${name}`);
      }

      try {
        const validate = ajv.compile(tool.inputSchema);
        const valid = validate(args);

        if (!valid) {
          return {
            content: [
              {
                type: "text" as const,
                text: JSON.stringify({
                  error: "Validation error",
                  details: validate.errors,
                }),
              },
            ],
            isError: true,
          };
        }

        let response;
        if (tool.isOpenApiTool) {
          response = await performOpenApiAction(
            tool,
            args as { params: any; body: any },
            currentJwt
          );
        } else if (tool.name === "CALL_API_REQUEST") {
          response = await performProxyApiRequest(
            args as ProxyApiRequestToolArgs,
            currentJwt
          );
        } else if (tool.name.split("_")[0] === "CUSTOM") {
          response = await performCustomAction(
            tool.name,
            args,
            currentJwt
          );
        } else {
          response = await performAction(
            tool.name,
            args,
            currentJwt
          );
        }

        if (response === null) {
          return {
            content: [
              {
                type: "text" as const,
                text: JSON.stringify({
                  error: `Failed to execute tool: ${tool.name}`,
                }),
              },
            ],
            isError: true,
          };
        }

        return {
          content: [{ type: "text" as const, text: JSON.stringify(response) }],
        };
      } catch (error: any | JsonResponseError | UserNotConnectedError) {
        if (error instanceof UserNotConnectedError) {
          let setupUrl;
          try {
            let userId = decodeJwt(currentJwt)?.payload.sub as string;
            if (!userId) {
              throw new Error("User ID not found");
            }
            setupUrl = await generateSetupLink({
              projectId: envs.PROJECT_ID,
              integrationName:
                tool.name === "CALL_API_REQUEST"
                  ? (args as ProxyApiRequestToolArgs).integration
                  : tool.integrationName,
              userId,
            });

            return {
              content: [
                {
                  type: "text",
                  text: `The ${tool.integrationName} integration is not enabled for the user. To set it up and use this tool, the user will need to visit: ${setupUrl}.

Instruct the user to set up their ${tool.integrationName} integration by visiting the link. Format the setup link in Markdown.`,
                },
              ],
              isError: false,
            };
          } catch (generateError) {
            error = generateError;
          }
        }

        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify({
                error: error.message,
              }),
            },
          ],
          isError: true,
        };
      }
    }
  );
}
